### ISSUE TITLE
Incompatibe with pypy3.7

### ISSUE THREAD

**Issue by lvella** [python-dugong/python-dugong#8]
I just download pypy 3.7 v7.3.3 and tried to install dugong in a pypy virtualenv. It failed with the following error:

```
$ pip install dugong
Collecting dugong
  Using cached dugong-3.8.1.tar.gz (317 kB)
Building wheels for collected packages: dugong
  Building wheel for dugong (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lucas/storage/src/venv/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5mf7ad8c
       cwd: /tmp/pip-install-fjx8pz2w/dugong/
  Complete output (47 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/dugong
  copying ./dugong/__init__.py -> build/lib/dugong
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fjx8pz2w/dugong/setup.py", line 108, in <module>
      main()
    File "/tmp/pip-install-fjx8pz2w/dugong/setup.py", line 63, in main
      'release': ('setup.py', dugong.__version__) }},
    File "/home/lucas/storage/src/venv/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lucas/storage/src/venv/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lucas/storage/src/venv/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/command/install.py", line 577, in run
      self.run_command(cmd_name)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 984, in run_command
      cmd_obj.ensure_finalized()
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/home/lucas/storage/src/venv/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
      self.set_undefined_options('install',('install_layout','install_layout'))
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 290, in set_undefined_options
      setattr(self, dst_option, getattr(src_cmd_obj, src_option))
    File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: install_layout
  ----------------------------------------
  ERROR: Failed building wheel for dugong
  Running setup.py clean for dugong
Failed to build dugong
Installing collected packages: dugong
    Running setup.py install for dugong ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lucas/storage/src/venv/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-759n8x2d/install-record.txt --single-version-externally-managed --compile --install-headers /home/lucas/storage/src/venv/include/site/python3.7/dugong
         cwd: /tmp/pip-install-fjx8pz2w/dugong/
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/dugong
    copying ./dugong/__init__.py -> build/lib/dugong
    running install_lib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fjx8pz2w/dugong/setup.py", line 108, in <module>
        main()
      File "/tmp/pip-install-fjx8pz2w/dugong/setup.py", line 63, in main
        'release': ('setup.py', dugong.__version__) }},
      File "/home/lucas/storage/src/venv/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lucas/storage/src/venv/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/command/install.py", line 577, in run
        self.run_command(cmd_name)
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/lucas/storage/src/venv/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/home/lucas/storage/src/pypy3.7-v7.3.3-linux64/lib-python/3/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lucas/storage/src/venv/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fjx8pz2w/dugong/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-759n8x2d/install-record.txt --single-version-externally-managed --compile --install-headers /home/lucas/storage/src/venv/include/site/python3.7/dugong Check the logs for full command output.
```

It came to me as a surprise, because dugong is pure Python. Perhaps this is just a minor installation issue?

**Comment by lvella** [comment]
It seems it was just outdated setuputils and pip.
